before_script:
  - sudo docker info
  - sudo apt-get -t jessie-backports install -y golang-1.6 golang

stages:
  - setup_env
  - build

setup_go_env_job:
  stage: setup_env
  script:
    - mkdir -p $HOME/gopath
    - export GOPATH=$HOME/gopath
    - go get "github.com/beevik/etree" # Installing this automatically is better, but I'm an idiot

build_app_job:
  stage: build
  script:
    #- go get -v ./...
    - go build -o ./workerserver *.go
  artifacts:
    paths:
      - workerserver
